feature_importance:
  amount: 0.011367907747626305
  day: 0.003164779394865036
  decline_ext_rate_30d: 0.0047854771837592125
  hour: 0.0032986898440867662
  is_legal_entity: 0.0
  is_mei: 0.0032736423891037703
  is_night: 0.002548361197113991
  is_person: 0.005082018673419952
  is_weekend: 0.002851384924724698
  mc_atm_br_tx_out_count_last_15d: 0.006572078447788954
  mc_atm_br_tx_out_count_last_1y: 0.00838314276188612
  mc_atm_br_tx_out_count_lifetime: 0.0055435579270124435
  mc_billpay_br_count_last_15d: 0.001416048500686884
  mc_billpay_br_count_last_1y: 0.026797739788889885
  mc_billpay_br_count_lifetime: 0.025784006342291832
  mc_billpay_br_sum_last_15d: 0.006585555151104927
  mc_billpay_br_sum_last_1y: 0.009354716166853905
  mc_chip_tx_amount_decl_ext_sum_30d: 0.0038109375163912773
  mc_chip_tx_amount_local_decl_ext_sum_15d: 0.004193184897303581
  mc_chip_tx_amount_local_succ_sum_15d: 0.011415086686611176
  mc_chip_tx_amount_succ_sum_30d: 0.007686992175877094
  mc_chip_tx_amount_succ_sum_7d: 0.008680960163474083
  mc_chip_tx_decl_ext_count_7d: 0.003148767864331603
  mc_chip_tx_succ_count_30d: 0.008999615907669067
  mc_chip_tx_succ_count_7d: 0.0027420332189649343
  mc_credit_transfer_in_br_count_last_30d: 0.0034699251409620047
  mc_credit_transfer_in_br_count_sanction_last_30d: 0.0
  mc_credit_transfer_in_br_sum_last_120d: 0.003171023912727833
  mc_credit_transfer_in_br_sum_last_15d: 0.0037204192485660315
  mc_credit_transfer_in_br_sum_last_180d: 0.004558205604553223
  mc_credit_transfer_in_br_sum_last_60d: 0.0032771711703389883
  mc_credit_transfer_in_br_sum_last_90d: 0.004510730970650911
  mc_credit_transfer_in_rounded_amounts_br_sum_last_30d: 0.002789363032206893
  mc_credit_transfer_out_br_count_last_15d: 0.0052218264900147915
  mc_credit_transfer_out_br_count_last_1y: 0.004047826398164034
  mc_credit_transfer_out_br_count_lifetime: 0.007113039493560791
  mc_credit_transfer_out_br_count_sanction_last_30d: 0.007171192206442356
  mc_credit_transfer_out_br_sum_last_15d: 0.0037451921962201595
  mc_credit_transfer_out_br_sum_last_1y: 0.0041961995884776115
  mc_credit_transfer_out_br_sum_last_30d: 0.003998638596385717
  mc_credit_transfer_out_rounded_amounts_br_count_last_30d: 0.002825345378369093
  mc_credit_transfer_out_rounded_amounts_br_sum_last_30d: 0.003157905302941799
  mc_merchants_ip_count_dist_shared_last_15d: 0.0033713493030518293
  mc_pur_br_count_last_15d: 0.003929274622350931
  mc_pur_br_count_last_1y: 0.004724246449768543
  mc_pur_br_count_lifetime: 0.0034173745661973953
  mc_pur_br_sum_last_15d: 0.003871789900586009
  mc_pur_br_sum_last_1y: 0.004332087468355894
  mc_sanction_count_last_2d: 0.0
  mc_tx_amount_decl_ext_sum_last_14d: 0.005370182450860739
  mc_tx_amount_decl_ext_sum_last_24h: 0.004031933378428221
  mc_tx_amount_decl_ext_sum_last_60m: 0.011100918054580688
  mc_tx_amount_decl_ext_sum_lifetime: 0.004467550199478865
  mc_tx_amount_decl_int_sum_lifetime: 0.014503449201583862
  mc_tx_amount_fail_sum_last_14d: 0.005620445590466261
  mc_tx_amount_fail_sum_last_60m: 0.011076575145125389
  mc_tx_amount_fail_sum_lifetime: 0.0037185524124652147
  mc_tx_amount_pend_sum_last_2d: 0.0
  mc_tx_amount_succ_sum_last_14d: 0.004415348172187805
  mc_tx_amount_succ_sum_last_24h: 0.004627875983715057
  mc_tx_amount_succ_sum_last_2d: 0.0030559434089809656
  mc_tx_amount_succ_sum_last_30d: 0.00594323268160224
  mc_tx_amount_succ_sum_last_60m: 0.0034098366741091013
  mc_tx_amount_succ_sum_last_90d: 0.003412392223253846
  mc_tx_amount_succ_sum_lifetime: 0.01846039481461048
  mc_tx_amount_sum_last_14d: 0.005078009329736233
  mc_tx_amount_sum_last_24h: 0.0034911949187517166
  mc_tx_amount_sum_last_2d: 0.0029079134110361338
  mc_tx_amount_sum_last_60m: 0.004474052228033543
  mc_tx_amount_sum_lifetime: 0.003731221193447709
  mc_tx_count_decl_ext_last_30d: 0.005093120504170656
  mc_tx_cp_count_decl_ext_last_24h: 0.005516550503671169
  mc_tx_cp_count_decl_ext_last_30d: 0.007041416130959988
  mc_tx_cp_dbt_sum_sq_decl_ext_last_30d: 0.0031175492331385612
  mc_tx_cp_dbt_sum_sq_fail_last_14d: 0.003823990235105157
  mc_tx_cp_dbt_sum_sq_fail_last_24h: 0.003472407115623355
  mc_tx_cp_mean_decl_ext_last_31d_mw: 0.004796919878572226
  mc_tx_cp_sum_decl_ext_last_24h: 0.005959860049188137
  mc_tx_cp_sum_decl_ext_last_30d: 0.004189772997051477
  mc_tx_succ_count_last_14d: 0.004972959402948618
  mc_tx_succ_count_last_24h: 0.004635953344404697
  mc_tx_succ_count_last_2d: 0.004971601068973541
  mc_tx_succ_count_last_30d: 0.004847828298807144
  mc_tx_succ_count_last_365d: 0.003843865357339382
  mc_tx_succ_count_last_60m: 0.003538896329700947
  mc_tx_succ_count_lifetime: 0.5096822381019592
  mc_weeks_signup: 0.007011503912508488
  mcc_count_succ_1y: 0.003687651827931404
  mcc_sum_sq_succ_1y: 0.0037674016784876585
  mcc_sum_sq_succ_30d: 0.0035697356797754765
  mcc_sum_succ_1y: 0.004722475074231625
  mcc_sum_succ_30d: 0.0032961999531835318
  month: 0.003436224302276969
feature_names:
- amount
- mc_weeks_signup
- mc_atm_br_tx_out_count_lifetime
- mc_credit_transfer_out_br_sum_last_30d
- mc_billpay_br_sum_last_15d
- mc_billpay_br_count_last_1y
- mc_credit_transfer_out_br_sum_last_1y
- mc_pur_br_count_last_1y
- mc_billpay_br_count_last_15d
- mc_atm_br_tx_out_count_last_1y
- mc_sanction_count_last_2d
- mc_credit_transfer_in_rounded_amounts_br_sum_last_30d
- mc_pur_br_sum_last_15d
- mc_credit_transfer_in_br_sum_last_180d
- mc_credit_transfer_out_br_count_lifetime
- mc_credit_transfer_out_br_count_sanction_last_30d
- mc_credit_transfer_out_br_count_last_15d
- mc_pur_br_count_last_15d
- mc_credit_transfer_in_br_sum_last_120d
- mc_pur_br_count_lifetime
- mc_credit_transfer_in_br_count_last_30d
- mc_credit_transfer_in_br_sum_last_90d
- mc_credit_transfer_out_br_count_last_1y
- mc_billpay_br_sum_last_1y
- mc_credit_transfer_out_rounded_amounts_br_sum_last_30d
- mc_credit_transfer_out_br_sum_last_15d
- mc_credit_transfer_in_br_count_sanction_last_30d
- mc_credit_transfer_in_br_sum_last_15d
- mc_billpay_br_count_lifetime
- mc_atm_br_tx_out_count_last_15d
- mc_credit_transfer_out_rounded_amounts_br_count_last_30d
- mc_credit_transfer_in_br_sum_last_60d
- mc_pur_br_sum_last_1y
- mc_chip_tx_succ_count_30d
- mc_chip_tx_decl_ext_count_7d
- mc_chip_tx_amount_local_decl_ext_sum_15d
- mc_chip_tx_amount_succ_sum_7d
- mc_chip_tx_amount_local_succ_sum_15d
- mc_chip_tx_amount_decl_ext_sum_30d
- mc_chip_tx_amount_succ_sum_30d
- mc_chip_tx_succ_count_7d
- decline_ext_rate_30d
- mc_tx_cp_mean_decl_ext_last_31d_mw
- mc_tx_amount_sum_last_60m
- mc_tx_amount_decl_ext_sum_lifetime
- mc_tx_amount_succ_sum_last_30d
- mc_tx_succ_count_last_24h
- mc_tx_amount_succ_sum_last_14d
- mc_tx_amount_fail_sum_last_60m
- mc_tx_amount_succ_sum_last_60m
- mc_tx_amount_succ_sum_last_2d
- mc_tx_amount_succ_sum_last_90d
- mc_tx_amount_fail_sum_last_14d
- mc_tx_amount_succ_sum_lifetime
- mc_tx_amount_pend_sum_last_2d
- mc_tx_amount_decl_int_sum_lifetime
- mc_tx_amount_sum_last_24h
- mc_tx_amount_sum_lifetime
- mc_tx_succ_count_last_14d
- mc_tx_succ_count_lifetime
- mc_tx_amount_succ_sum_last_24h
- mc_tx_amount_decl_ext_sum_last_14d
- mc_tx_amount_decl_ext_sum_last_24h
- mc_tx_amount_decl_ext_sum_last_60m
- mc_tx_succ_count_last_2d
- mc_tx_amount_fail_sum_lifetime
- mc_tx_succ_count_last_30d
- mc_tx_amount_sum_last_2d
- mc_tx_succ_count_last_365d
- mc_tx_succ_count_last_60m
- mc_tx_amount_sum_last_14d
- mc_tx_cp_sum_decl_ext_last_24h
- mc_tx_cp_dbt_sum_sq_decl_ext_last_30d
- mc_tx_count_decl_ext_last_30d
- mc_tx_cp_sum_decl_ext_last_30d
- mc_tx_cp_count_decl_ext_last_24h
- mc_tx_cp_dbt_sum_sq_fail_last_24h
- mc_tx_cp_count_decl_ext_last_30d
- mc_tx_cp_dbt_sum_sq_fail_last_14d
- mc_merchants_ip_count_dist_shared_last_15d
- mcc_sum_succ_1y
- mcc_sum_sq_succ_30d
- mcc_count_succ_1y
- mcc_sum_sq_succ_1y
- mcc_sum_succ_30d
- is_legal_entity
- is_mei
- is_person
- is_weekend
- is_night
- month
- day
- hour
model_parameters:
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: null
  device: null
  early_stopping_rounds: null
  enable_categorical: false
  eval_metric: aucpr
  feature_types: null
  gamma: null
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: 0.1
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: 5
  max_leaves: null
  min_child_weight: null
  missing: .nan
  monotone_constraints: null
  multi_strategy: null
  n_estimators: 500
  n_jobs: null
  num_parallel_tree: null
  objective: binary:logistic
  random_state: null
  reg_alpha: null
  reg_lambda: null
  sampling_method: null
  scale_pos_weight: null
  subsample: null
  tree_method: null
  use_label_encoder: false
  validate_parameters: null
  verbosity: null
model_type: XGBoost
performance_metrics:
  Avg Precision: 0.45109057704340333
  F1-Score: 0.33228070175438595
  Precision: 0.2035683576956148
  Precision@100: 0.7
  ROC_AUC: 0.9730766720195325
  Recall: 0.9036259541984732
preprocessing:
  random_state: 42
  sampling_strategy: 0.25
timestamp: '20250212_144931'
